option_settings:
  aws:elasticbeanstalk:container:nodejs:
    NodeCommand: "npm start"
branch-defaults:
  master:
    environment: product-description-env2
    group_suffix: null
environment-defaults:
  product-description-dev:
    branch: null
    repository: null
  product-description-env:
    branch: null
    repository: null
  product-description-env2:
    branch: null
    repository: null
global:
  application_name: product-description
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
